In [1]:
# Importando o NumPy
import numpy as np

In [2]:
np.__version__

'1.15.2'

# Criando arrays 

In [9]:
# Help
help(np.array)

<function numpy.core.multiarray.array>

In [4]:
vetor1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
print(vetor1)

[0 1 2 3 4 5 6 7 8]


In [6]:
type(vetor1)

numpy.ndarray

In [7]:
# calcular a soma acumulada
vetor1.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [10]:
# Percebendo como listas e arrays sao objetos diferentes
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [11]:
type(lst)

list

In [12]:
vetor1[0]

0

In [13]:
vetor1[0] = 100

In [14]:
print(vetor1)

[100   1   2   3   4   5   6   7   8]


In [15]:
# verificando o formato do array , vetor uni-dimensional
print(vetor1.shape)

(9,)
