In [1]:
# Importando o NumPy
import numpy as np

In [2]:
np.__version__

'1.15.2'

# Criando arrays 

In [9]:
# Help
help(np.array)

<function numpy.core.multiarray.array>

In [4]:
vetor1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
print(vetor1)

[0 1 2 3 4 5 6 7 8]


In [6]:
type(vetor1)

numpy.ndarray

In [7]:
# calcular a soma acumulada
vetor1.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [10]:
# Percebendo como listas e arrays sao objetos diferentes
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [11]:
type(lst)

list

In [12]:
vetor1[0]

0

In [13]:
vetor1[0] = 100

In [14]:
print(vetor1)

[100   1   2   3   4   5   6   7   8]


In [16]:
# verificando o formato do array , vetor uni-dimensional
print(vetor1.shape)

(9,)


In [17]:
# A função arange cria um vetor contendo uma progressão aritmética a partir de um intervalo - start, stop, step
vetor2 = np.arange(0., 4.5, .5)

In [18]:
print(vetor2)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]


In [19]:
type(vetor2)

numpy.ndarray

In [20]:
np.shape(vetor2)

(9,)

In [21]:
print(vetor2.dtype)

float64


In [22]:
x = np.arange(1, 10, 0.25)
print(x)

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.   4.25
 4.5  4.75 5.   5.25 5.5  5.75 6.   6.25 6.5  6.75 7.   7.25 7.5  7.75
 8.   8.25 8.5  8.75 9.   9.25 9.5  9.75]


In [24]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
# Retorna 1 nas posições em diagonal e 0 no restante
z = np.eye(3)

In [26]:
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
# Os valores passados como parâmetro, formam uma diagonal# Os val
d = np.diag(np.array([1, 2, 3, 4]))

In [29]:
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [30]:
# Array de números complexos
c = np.array([1+2j, 3+4j, 5+6*1j])

In [31]:
c

array([1.+2.j, 3.+4.j, 5.+6.j])

In [32]:
# Arrays de valores booleanos
b = np.array([True, False, False, True])

In [33]:
b

array([ True, False, False,  True])

In [35]:
# Array de strings
s = np.array(['Python', 'R', 'Julia'])

In [36]:
s

array(['Python', 'R', 'Julia'], dtype='<U6')

In [37]:
# O método linspace (linearly spaced vector) retorna um número de 
# valores igualmente distribuídos no intervalo especificado 
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [43]:
print(np.linspace(0, 10, 15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [47]:
print(np.logspace(0, 5, 10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]


# Criando Matrizes 

In [2]:
# Criando matrizes é um array bi-dimensional e um tensor é um array tri-dimensional
matriz = np.array([[1,2,3],[4,5,6]])

In [3]:
print(matriz)

[[1 2 3]
 [4 5 6]]


In [5]:
# Mostra que temos uma matriz 2 linhas por 3 colunas
print(matriz.shape)

(2, 3)


In [6]:
# Criando uma matriz 2x3 apenas com números "1"
matriz1 = np.ones((2,3))

In [7]:
print(matriz1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# Criando uma matriz a partir de uma lista de listas
lista = [[13,81,22], [0, 34, 59], [21, 48, 94]]

In [9]:
# A função matrix cria uma matria a partir de uma sequência
matriz2 = np.matrix(lista)

In [10]:
print(matriz2)

[[13 81 22]
 [ 0 34 59]
 [21 48 94]]


In [11]:
type(matriz2)

numpy.matrixlib.defmatrix.matrix

In [12]:
# Formato da matriz
np.shape(matriz2)

(3, 3)

In [13]:
matriz2.size

9

In [14]:
print(matriz2.dtype)

int64


In [16]:
matriz2.itemsize

8

In [17]:
matriz2.nbytes

72

In [19]:
print(matriz2[2,1])

48


In [22]:
# Alterando um elemento na matriz
matriz2[1,0] = 100

In [23]:
matriz2

matrix([[ 13,  81,  22],
        [100,  34,  59],
        [ 21,  48,  94]])

In [25]:
x = np.array([1, 2])  # NumPy decide o tipo dos dados
y = np.array([1.0, 2.0])  # NumPy decide o tipo dos dados
z = np.array([1, 2], dtype=np.float64) # # Forçamos um tipo de dado em particular

print(x.dtype, y.dtype, z.dtype)

int64 float64 float64


In [26]:
matriz3 = np.array([[24, 76], [35, 89]], dtype=float)

In [28]:
matriz3

array([[24., 76.],
       [35., 89.]])

In [29]:
matriz3.itemsize

8

In [30]:
matriz3.nbytes

32

In [31]:
# Verificar quantas dimensoes tem a matriz
matriz3.ndim

2

In [32]:
matriz3[1,1]

89.0

In [ ]:
matriz3[1,1] = 100